//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryIt.XMLServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XMLServiceReference.IXMLServices")]
    public interface IXMLServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLServices/verification", ReplyAction="http://tempuri.org/IXMLServices/verificationResponse")]
        string verification(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLServices/verification", ReplyAction="http://tempuri.org/IXMLServices/verificationResponse")]
        System.Threading.Tasks.Task<string> verificationAsync(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLServices/XPathSearch", ReplyAction="http://tempuri.org/IXMLServices/XPathSearchResponse")]
        string XPathSearch(string xmlUrl, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLServices/XPathSearch", ReplyAction="http://tempuri.org/IXMLServices/XPathSearchResponse")]
        System.Threading.Tasks.Task<string> XPathSearchAsync(string xmlUrl, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXMLServicesChannel : TryIt.XMLServiceReference.IXMLServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XMLServicesClient : System.ServiceModel.ClientBase<TryIt.XMLServiceReference.IXMLServices>, TryIt.XMLServiceReference.IXMLServices {
        
        public XMLServicesClient() {
        }
        
        public XMLServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XMLServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string verification(string xmlUrl, string xsdUrl) {
            return base.Channel.verification(xmlUrl, xsdUrl);
        }
        
        public System.Threading.Tasks.Task<string> verificationAsync(string xmlUrl, string xsdUrl) {
            return base.Channel.verificationAsync(xmlUrl, xsdUrl);
        }
        
        public string XPathSearch(string xmlUrl, string path) {
            return base.Channel.XPathSearch(xmlUrl, path);
        }
        
        public System.Threading.Tasks.Task<string> XPathSearchAsync(string xmlUrl, string path) {
            return base.Channel.XPathSearchAsync(xmlUrl, path);
        }
    }
}
